/* 오늘 뭐 먹지 - 메뉴 데이터
   meals: lunch, dinner (둘 다 해당하면 배열에 둘 다 포함)
   tags: 매운맛, 다이어트, 든든한, 국물, 간편한, 혼밥, 해장, 채식가능
*/
const MENU_DATA = [
  { name: "김치찌개", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "매운맛", "혼밥"], desc: "얼큰한 국물에 밥 한 그릇, 실패 없는 국민 메뉴." },
  { name: "된장찌개", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "혼밥", "다이어트"], desc: "구수하고 든든한 집밥 느낌의 찌개." },
  { name: "제육볶음", cat: "한식", meals: ["lunch", "dinner"], tags: ["매운맛", "든든한"], desc: "매콤달콤 양념에 볶은 돼지고기, 밥도둑 메뉴." },
  { name: "불고기", cat: "한식", meals: ["lunch", "dinner"], tags: ["든든한"], desc: "달큰한 양념의 소고기 불고기, 남녀노소 인기 메뉴." },
  { name: "비빔밥", cat: "한식", meals: ["lunch", "dinner"], tags: ["다이어트", "혼밥", "채식가능"], desc: "나물과 밥을 슥슥 비벼 먹는 균형 잡힌 한 끼." },
  { name: "순두부찌개", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "매운맛", "혼밥"], desc: "부드러운 순두부와 얼큰한 국물의 조합." },
  { name: "삼겹살", cat: "한식", meals: ["dinner"], tags: ["든든한"], desc: "굽고 쌈 싸 먹는 대표 회식·저녁 메뉴." },
  { name: "갈비탕", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "든든한", "해장"], desc: "깊은 국물맛의 든든한 보양식." },
  { name: "설렁탕", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "해장"], desc: "뽀얀 국물이 속을 편안하게 해주는 메뉴." },
  { name: "냉면", cat: "한식", meals: ["lunch", "dinner"], tags: ["간편한"], desc: "시원하게 즐기는 여름 별미 면 요리." },
  { name: "칼국수", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "든든한"], desc: "쫄깃한 면발과 뜨끈한 국물이 매력인 메뉴." },
  { name: "떡볶이", cat: "분식", meals: ["lunch", "dinner"], tags: ["매운맛", "간편한"], desc: "언제 먹어도 당기는 국민 분식 메뉴." },
  { name: "김밥", cat: "분식", meals: ["lunch"], tags: ["간편한", "혼밥"], desc: "빠르고 간편하게 즐기는 한 끼." },
  { name: "라면", cat: "분식", meals: ["lunch", "dinner"], tags: ["간편한", "혼밥"], desc: "언제나 옳은 초간단 야식·한 끼 메뉴." },
  { name: "돈까스", cat: "한식", meals: ["lunch", "dinner"], tags: ["든든한", "혼밥"], desc: "바삭한 튀김옷의 남녀노소 인기 메뉴." },
  { name: "짜장면", cat: "중식", meals: ["lunch", "dinner"], tags: ["간편한", "혼밥"], desc: "달콤짭짤한 소스의 대표 중식 면 요리." },
  { name: "짬뽕", cat: "중식", meals: ["lunch", "dinner"], tags: ["국물", "매운맛"], desc: "얼큰한 국물과 해산물의 조화." },
  { name: "탕수육", cat: "중식", meals: ["dinner"], tags: ["든든한"], desc: "바삭달콤한 소스의 인기 중식 요리, 여럿이 먹기 좋음." },
  { name: "마라탕", cat: "중식", meals: ["lunch", "dinner"], tags: ["매운맛", "국물"], desc: "얼얼하고 중독적인 매운맛의 중국식 국물 요리." },
  { name: "볶음밥", cat: "중식", meals: ["lunch", "dinner"], tags: ["간편한", "혼밥"], desc: "간단하지만 든든한 중식 한 끼." },
  { name: "초밥", cat: "일식", meals: ["lunch", "dinner"], tags: ["다이어트"], desc: "신선한 재료로 즐기는 깔끔한 한 끼." },
  { name: "돈코츠라멘", cat: "일식", meals: ["lunch", "dinner"], tags: ["국물", "든든한"], desc: "진한 돼지뼈 육수의 진한 일본식 라멘." },
  { name: "우동", cat: "일식", meals: ["lunch", "dinner"], tags: ["국물", "간편한"], desc: "쫄깃한 면발의 담백한 국물 요리." },
  { name: "규동", cat: "일식", meals: ["lunch", "dinner"], tags: ["간편한", "혼밥"], desc: "달큰한 소고기덮밥, 빠르게 먹기 좋은 메뉴." },
  { name: "가츠동", cat: "일식", meals: ["lunch", "dinner"], tags: ["든든한", "혼밥"], desc: "바삭한 돈까스를 올린 든든한 덮밥." },
  { name: "오코노미야키", cat: "일식", meals: ["dinner"], tags: ["든든한"], desc: "일본식 부침개, 술안주로도 좋은 메뉴." },
  { name: "파스타", cat: "양식", meals: ["lunch", "dinner"], tags: ["혼밥"], desc: "면과 소스의 다양한 조합을 즐기는 서양 요리." },
  { name: "리조또", cat: "양식", meals: ["lunch", "dinner"], tags: ["든든한"], desc: "크리미한 소스와 쌀알의 조화가 매력인 메뉴." },
  { name: "스테이크", cat: "양식", meals: ["dinner"], tags: ["든든한"], desc: "특별한 저녁 식사에 잘 어울리는 메뉴." },
  { name: "피자", cat: "양식", meals: ["lunch", "dinner"], tags: ["든든한"], desc: "치즈 가득한 만족스러운 한 끼, 배달로도 인기." },
  { name: "샌드위치", cat: "양식", meals: ["lunch"], tags: ["간편한", "다이어트", "혼밥"], desc: "빠르게 먹을 수 있는 가벼운 한 끼." },
  { name: "샐러드", cat: "양식", meals: ["lunch"], tags: ["다이어트", "채식가능", "혼밥"], desc: "가볍고 건강하게 즐기는 저칼로리 메뉴." },
  { name: "쌀국수", cat: "아시안", meals: ["lunch", "dinner"], tags: ["국물", "다이어트", "혼밥"], desc: "담백한 육수와 향신료가 어우러진 베트남 면 요리." },
  { name: "팟타이", cat: "아시안", meals: ["lunch", "dinner"], tags: ["간편한"], desc: "새콤달콤한 태국식 볶음면." },
  { name: "똠얌꿍", cat: "아시안", meals: ["dinner"], tags: ["국물", "매운맛"], desc: "새콤매콤한 태국식 국물 요리." },
  { name: "카레라이스", cat: "아시안", meals: ["lunch", "dinner"], tags: ["간편한", "혼밥"], desc: "부드러운 카레와 밥의 든든한 조합." },
  { name: "닭갈비", cat: "한식", meals: ["dinner"], tags: ["매운맛", "든든한"], desc: "매콤한 양념에 볶은 닭고기, 여럿이 먹기 좋은 메뉴." },
  { name: "치킨", cat: "한식", meals: ["dinner"], tags: ["든든한"], desc: "바삭한 튀김의 대표 야식·회식 메뉴." },
  { name: "족발", cat: "한식", meals: ["dinner"], tags: ["든든한"], desc: "쫀득한 식감의 인기 야식 메뉴." },
  { name: "보쌈", cat: "한식", meals: ["dinner"], tags: ["든든한"], desc: "부드러운 수육과 김치의 조화." },
  { name: "곱창", cat: "한식", meals: ["dinner"], tags: ["든든한", "해장"], desc: "고소하고 쫄깃한 식감의 인기 술안주 메뉴." },
  { name: "육개장", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "매운맛", "해장"], desc: "얼큰하고 든든한 국물 요리." },
  { name: "콩나물국밥", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "해장", "혼밥"], desc: "시원한 국물로 속을 풀어주는 해장 메뉴." },
  { name: "북엇국", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "해장"], desc: "담백하고 시원한 대표 해장 메뉴." },
  { name: "샤브샤브", cat: "한식", meals: ["dinner"], tags: ["다이어트", "국물"], desc: "신선한 채소와 얇은 고기를 데쳐 먹는 건강식." },
  { name: "냉모밀", cat: "일식", meals: ["lunch"], tags: ["간편한", "다이어트"], desc: "시원하게 즐기는 여름철 별미 면 요리." },
  { name: "닭가슴살 도시락", cat: "양식", meals: ["lunch"], tags: ["다이어트", "혼밥"], desc: "고단백 저칼로리로 관리하기 좋은 메뉴." },
  { name: "도시락", cat: "한식", meals: ["lunch"], tags: ["간편한", "혼밥"], desc: "여러 반찬을 골고루 즐기는 간편한 한 끼." },
  { name: "편의점 삼각김밥", cat: "분식", meals: ["lunch", "dinner"], tags: ["간편한", "혼밥"], desc: "바쁠 때 가장 빠르고 저렴하게 해결하는 메뉴." },
  { name: "만두", cat: "중식", meals: ["lunch", "dinner"], tags: ["간편한"], desc: "속이 꽉 찬 든든한 한 끼 또는 안주." },
  { name: "월남쌈", cat: "아시안", meals: ["dinner"], tags: ["다이어트", "채식가능"], desc: "채소와 고기를 라이스페이퍼에 싸 먹는 건강식." },
  { name: "부대찌개", cat: "한식", meals: ["lunch", "dinner"], tags: ["국물", "매운맛", "든든한"], desc: "얼큰하고 푸짐한 인기 찌개 메뉴." },
  { name: "장어덮밥", cat: "일식", meals: ["dinner"], tags: ["든든한"], desc: "보양식으로도 인기 있는 든든한 덮밥." },
  { name: "훠궈", cat: "중식", meals: ["dinner"], tags: ["매운맛", "국물"], desc: "얼얼한 육수에 재료를 데쳐 먹는 중국식 샤브샤브." },
  { name: "닭볶음탕", cat: "한식", meals: ["dinner"], tags: ["매운맛", "든든한"], desc: "얼큰하고 든든한 닭요리, 밥과 함께 든든하게." },
  { name: "포케", cat: "양식", meals: ["lunch"], tags: ["다이어트", "혼밥", "채식가능"], desc: "다양한 토핑을 즐기는 하와이안 건강식 볼." },
  { name: "우육탕면", cat: "중식", meals: ["lunch", "dinner"], tags: ["국물", "든든한"], desc: "진한 소고기 육수의 든든한 면 요리." },
];
